Development p5
EgorTurets/iTechArt pull request #6
Opened 2017-08-10 15:35 UTC by EgorTurets

Problems:
1) Not implemented search / adding ads with the value "required / leased"
2) Configuring Webpack does not allow you to enter paths manually.
3) Use the div instead of the buttons (because of step 2).
4) Need to refactor.

2017-08-14 15:48 UTC, maryia-kabash requested changes
В проекте хорошо написаны контейнеры и отработана передача данных в презентационнные компоненты и изменение этих данных.
Хорошо написаны actions/actionCreators.
В качестве тренировки можно заменить некоторые компоненты на stateless.
CSS лучше писать без излишних уровней сложенности, по возможности обходиться только классами и тегами, без использования id. 
Структуру проекта имеет смысл переделать в соответствии с приведенной в лекции №12.

2017-08-14 15:48 UTC, maryia-kabash commented on P5/webpack.config.js
> +    devServer: {
Для правильного отображения страницы при перезагрузке devServer'у требуется указать опцию historyApiFallback

2017-08-14 15:48 UTC, maryia-kabash commented on P5/Controller/LogInController.js
> +        logIn : state.logInState,
имя очень похоже на LogIn из функции mapDispatchToProps - лучше заменить на logInState, например

2017-08-14 15:48 UTC, maryia-kabash commented on P5/View/LogInView.js
> +            <form className="form-inner-center">
Обработчик отправки формы должен находиться на событии onSubmit (иначе теряется фозможность отправить форму с помощью клавиши Enter). 
Для этого в форму необходимо добавить кнопку (вместо div className="button") и добавить e.preventDefault(); в функцию-обработчик. 
Этот комментарий относится ко всем формам в проекте.

2017-08-14 15:48 UTC, maryia-kabash commented on P5/View/LogInView.js
> +        if (this.props.logIn.isCanRedirect) {
isCanRedirect - грамматически неверно с т.зр. английского языка, лучше назвать canRedirect

2017-08-14 15:48 UTC, maryia-kabash commented on P5/Model/reducers/newNotificationReducer.js
> +                    metric: 0
Помимо сброса метрики до нуля было бы неплохо также сообщить пользователю, о том, что значение не может быть меньше нуля, это более user-friendly.

2017-08-14 15:48 UTC, maryia-kabash commented on P5/Model/reducers/logInReducer.js
> +            let allUsers = JSON.parse(window.sessionStorage.getItem('allUsers'));
Reducer должен быть "чистой функцией", т.е. использовать данные из sessionStorage здесь не стоит. Лучше их вынести в actionCreators. 
Этот комментарий относится ко всем подобным редюсерам в проекте.

2017-08-21 08:43 UTC, Turach approved these changes
Ok

2017-08-21 08:43 UTC, merged